/* NOTAM contractions — FAA JO 7340.2 as used in the domestic NOTAM system, plus the
   NOTAM keywords and the pieces the decoder on notam.html reads. One global, NOTAM_DICT:
   contraction as written -> plain form. Plain English words are left out on purpose so
   the decoder underlines only what needs decoding. */
window.NOTAM_DICT = {
  "(O)": "other", "(U)": "unverified", "A/C": "aircraft", "A/FD": "airport/facility directory",
  "A/G": "air to ground", AAF: "Army airfield", ABN: "aerodrome beacon", ABV: "above",
  ACAS: "airborne collision avoidance system", ACCUM: "accumulate", ACFT: "aircraft", ACR: "air carrier",
  ACRO: "aerobatic", ACT: "active", ACTL: "actual", ACTV: "active", ACTVT: "activate", AD: "aerodrome",
  ADDN: "additional", ADDNL: "additional", ADIZ: "air defense identification zone", ADJ: "adjacent",
  ADS: "automatic dependent surveillance", "ADS-B": "ADS-B (automatic dependent surveillance broadcast)",
  ADVS: "advise", ADVSY: "advisory", AFB: "Air Force base", AFD: "airport/facility directory (chart supplement)",
  AFSS: "automated flight service station", AFT: "after", AGL: "above ground level", AGN: "again",
  AIC: "aeronautical information circular", AIP: "aeronautical information publication",
  AIRAC: "aeronautical information regulation and control", AIRMET: "airmen’s meteorological information",
  AIRSPACE: "airspace", ALG: "along", ALS: "approach light system", ALSF: "ALS with sequenced flashers",
  ALSTG: "altimeter setting", ALT: "altitude", ALTM: "altimeter", ALTS: "altitudes", AMD: "amend", AMDD: "amended",
  AMDT: "amendment", ANGB: "Air National Guard base", ANT: "antenna", ANTI: "anti", AP: "airport", APCH: "approach",
  APP: "approach control", APPCON: "approach control", APPS: "approaches", APRON: "apron", APROX: "approximately",
  APRX: "approximately", APRXLY: "approximately", APV: "approve", APVD: "approved",
  ARFF: "aircraft rescue and fire fighting", ARPT: "airport", ARR: "arrival", ARRS: "arrivals",
  ARTCC: "air route traffic control center", ARWY: "airway", ASAP: "as soon as possible",
  ASDE: "airport surface detection equipment", ASN: "aeronautical study number",
  ASOS: "automated surface observing system", ASPH: "asphalt",
  ASR: "airport surveillance radar (or antenna structure registration number in OBST NOTAMs)",
  ATC: "air traffic control", ATCAA: "ATC assigned airspace", ATCT: "airport traffic control tower",
  ATIS: "automatic terminal information service", ATS: "air traffic services", ATTN: "attention", ATTND: "attended",
  ATZ: "aerodrome traffic zone", AUTH: "authorized", AVBL: "available", AWOS: "automated weather observing system",
  AWSS: "automated weather sensor system", AWY: "airway", BA: "braking action",
  "BARO-VNAV": "barometric vertical navigation", BC: "back course", BCN: "beacon", BCST: "broadcast", BFR: "before",
  BLDG: "building", BLN: "balloon", BLO: "below", BLW: "below", BND: "bound", BRAF: "braking action fair",
  BRAG: "braking action good", BRAN: "braking action nil", BRAP: "braking action poor", BRG: "bearing",
  BRKG: "braking", BRKN: "broken", BTN: "between", BTW: "between", BTWN: "between", BYD: "beyond", CAT: "category",
  CATS: "categories", CCLKWS: "counterclockwise", CD: "clearance delivery", CFA: "controlled firing area",
  CFM: "confirm", CFMD: "confirmed", CFR: "Code of Federal Regulations", CGAS: "Coast Guard air station",
  CHART: "chart", CHG: "change", CHGD: "changed", CIRC: "circling", CIRCLING: "circling", CLBG: "climbing",
  CLKWS: "clockwise", CLNC: "clearance", CLR: "clear", CLRD: "cleared", CLSD: "closed", CMPLT: "complete",
  CMSN: "commission", CMSND: "commissioned", CNL: "cancel", CNLD: "cancelled", CNTR: "center", CNTRD: "centered",
  CNTRLD: "controlled", CNTRLN: "centerline", CNTRLR: "controller", CNTRWY: "centre runway", COM: "communications",
  COMM: "communications", CONC: "concrete", COND: "condition", CONDS: "conditions", CONST: "construction",
  CONSTR: "construction", CONT: "continue", CONTD: "continued", CONTN: "continuous", COORD: "coordinates",
  COORDS: "coordinates", CPD: "coupled", CRIT: "critical", CRS: "course", CS: "chart supplement",
  CTA: "control area", CTAF: "common traffic advisory frequency", CTC: "contact", CTCT: "contact",
  CTLZ: "centerline", CTN: "caution", CTR: "center", "D-ATIS": "digital ATIS",
  "D-TPP": "digital terminal procedures publication", "D/T": "date/time", DA: "decision altitude", DALGT: "daylight",
  DATA: "data", DCMSN: "decommission", DCMSND: "decommissioned", DCT: "direct", DEACTV: "deactivate", DEG: "degrees",
  DEGRADED: "degraded", DEGS: "degrees", DEP: "departure", DEPCON: "departure control", DEPS: "departures",
  DER: "departure end of runway", DH: "decision height", DIR: "direction", DISPLCD: "displaced", DIST: "distance",
  DLA: "delay", DLAD: "delayed", DLT: "delete", DLTD: "deleted", DLY: "daily", DME: "distance measuring equipment",
  DP: "departure procedure", DRG: "during", DSCNT: "descent", DSPLCD: "displaced", DSTC: "distance",
  DTHR: "displaced threshold", DVFR: "defense VFR", EBND: "eastbound", EFAS: "en route flight advisory service",
  EFF: "effective", ELEV: "elevation", ELT: "emergency locator transmitter", EMERG: "emergency",
  ENE: "east-northeast", ENG: "engine", ENRT: "en route", ENTR: "entire", EQPT: "equipment", ESE: "east-southeast",
  EST: "estimated", ESTAB: "establish", ESTABD: "established", ETA: "estimated time of arrival",
  ETD: "estimated time of departure", EXC: "except", EXCL: "excluding", EXCP: "except", EXEC: "executive",
  EXPD: "expected", EXTD: "extend", EXTN: "extension", EXTND: "extended", FAC: "facility", FACS: "facilities",
  FAF: "final approach fix", FDC: "Flight Data Center", FICON: "field condition", FIR: "flight information region",
  FIREFIGHTING: "firefighting", FIS: "flight information service", "FIS-B": "flight information service broadcast",
  FIX: "fix", FL: "flight level", FLD: "field", FLW: "follow", FLWG: "following", FM: "from",
  FOD: "foreign object debris", FREQ: "frequency", FREQS: "frequencies", FRI: "Friday", FRM: "from", FRNT: "front",
  FRQ: "frequency", FRQNT: "frequent", FRZ: "flight restricted zone", FRZN: "frozen", FSS: "flight service station",
  FT: "feet", GA: "general aviation", GBAS: "ground based augmentation system", GCO: "ground communications outlet",
  GLDR: "glider", GND: "ground", GNDCON: "ground control", "GO-AROUND": "go around", GP: "glide path",
  GPS: "Global Positioning System", GRVL: "gravel", GS: "glideslope", HAA: "height above airport",
  HAL: "height above landing", HAT: "height above touchdown", HAZ: "hazard", HDG: "heading", HEL: "helicopter",
  HELI: "helicopter", HELIPAD: "helipad", HGT: "height", HIAL: "high intensity approach lights",
  HILPT: "hold in lieu of procedure turn", HIRL: "high intensity runway lights",
  HITL: "high intensity taxiway lights", HIWAS: "hazardous in-flight weather advisory service", HLD: "hold",
  HLDG: "holding", HORIZ: "horizontal", HR: "hour", HRS: "hours", HS: "hot spot", HVY: "heavy", HWY: "highway",
  IAF: "initial approach fix", IAP: "instrument approach procedure", IAS: "indicated airspeed",
  IAW: "in accordance with", ICG: "icing", IDENT: "identification", IF: "intermediate fix", IFO: "in front of",
  IFR: "instrument flight rules", ILS: "instrument landing system", IM: "inner marker",
  IMC: "instrument meteorological conditions", IMDT: "immediate", IMDTLY: "immediately", INBD: "inbound",
  INCL: "include", INCLD: "included", INCLG: "including", INCURSION: "incursion", INDEFLY: "indefinitely",
  INFLT: "in flight", INFO: "information", INOP: "inoperative", INS: "inches", INSTL: "install", INSTLD: "installed",
  INSTR: "instructions", INT: "intersection", INTL: "international", INTMT: "intermittent", INTSF: "intensify",
  INTST: "intensity", INTSTY: "intensity", INTXN: "intersection", IR: "ice on runway", JDAY: "Julian day",
  KIAS: "knots indicated airspeed", KT: "knots", KTS: "knots", LAHSO: "land and hold short operations",
  LAT: "latitude", LCL: "local", LCTD: "located", LDA: "localizer type directional aid", LDG: "landing",
  LDGS: "landings", LEN: "length", LGT: "light", LGTD: "lighted", LGTG: "lighting", LGTH: "length", LGTS: "lights",
  LIRL: "low intensity runway lights", LLWAS: "low level wind shear alert system", LLWS: "low level wind shear",
  LLZ: "localizer", LMM: "compass locator at middle marker", LMTD: "limited", LNAV: "lateral navigation",
  LOA: "letter of agreement", LOC: "localizer", LOM: "compass locator at outer marker", LONG: "longitude",
  LPV: "localizer performance with vertical guidance", LRG: "large", LTA: "letter to airmen", LTD: "limited",
  LTP: "left traffic pattern", LTS: "lights", LWR: "lower", LYR: "layer", MAA: "maximum authorized altitude",
  MAG: "magnetic", MAINT: "maintenance", MALS: "medium intensity ALS", MALSF: "MALS with sequenced flashers",
  MALSR: "MALS with RAIL", MAP: "missed approach point", MAPT: "missed approach point", MAX: "maximum",
  MCA: "minimum crossing altitude", MCAS: "Marine Corps air station", MCOTS: "may cause out of service",
  MDA: "minimum descent altitude", MEA: "minimum en route altitude", MEDEVAC: "medical evacuation",
  MEHT: "minimum eye height over threshold", MEML: "memorial", METAR: "aviation routine weather report",
  MIL: "military", MIN: "minimum", MINS: "minutes", MIRL: "medium intensity runway lights",
  MITL: "medium intensity taxiway lights", MKD: "marked", MKR: "marker", MKRS: "markers",
  MLS: "microwave landing system", MM: "middle marker", MNM: "minimum", MNMS: "minimums", MNT: "monitor",
  MNTN: "maintain", MOA: "military operations area", MOCA: "minimum obstruction clearance altitude", MON: "Monday",
  "MON-FRI": "Monday through Friday", MPH: "miles per hour", MRA: "minimum reception altitude",
  MSA: "minimum safe altitude", MSG: "message", MSL: "mean sea level", MTN: "mountain",
  MTR: "military training route", MUNI: "municipal", MVA: "minimum vectoring altitude", MVFR: "marginal VFR",
  NA: "not authorized", NAF: "naval air facility", NANU: "notice advisory to NAVSTAR users",
  NAS: "naval air station (or National Airspace System)", NATL: "national", NAV: "navigation aid",
  NBND: "northbound", NDB: "nondirectional beacon", NE: "northeast", NET: "not earlier than", NGT: "night",
  NLT: "not later than", NM: "nautical miles", NMRS: "numerous", NNE: "north-northeast", NNW: "north-northwest",
  "NON-PRECISION": "nonprecision", NONSTD: "nonstandard", NOTAM: "notice to air missions",
  NOTAMC: "cancellation NOTAM", NOTAMN: "new NOTAM", NOTAMR: "replacement NOTAM", NPI: "nonprecision instrument",
  NR: "near", NRW: "narrow", NSA: "national security area", NSTD: "nonstandard", NW: "northwest", NXT: "next",
  OBSC: "obscured", OBST: "obstruction", OBSTN: "obstruction", OBSTNS: "obstructions", OCNL: "occasional",
  OCNLY: "occasionally", ODALS: "omnidirectional ALS", ODP: "obstacle departure procedure", OFST: "offset",
  OFZ: "obstacle free zone", OM: "outer marker", OPN: "open", OPNS: "operations", OPR: "operate", OPRG: "operating",
  OPS: "operations", ORIG: "original", ORIGD: "originated", OTLK: "outlook", OTS: "out of service",
  OUTBD: "outbound", OVC: "overcast", OVR: "over", PAEW: "personnel and equipment working",
  PAPI: "precision approach path indicator", PAR: "precision approach radar", PARL: "parallel", PAX: "passengers",
  PCL: "pilot controlled lighting", PCT: "percent", PERM: "permanent", PIREP: "pilot weather report",
  PJE: "parachute jumping exercise", PLA: "practice low approach", PLASI: "pulsating VASI", POSN: "position",
  POTUS: "the President", PPD: "prepaid", PPR: "prior permission required", PRELIM: "preliminary", PRIM: "primary",
  PRKG: "parking", PRN: "pseudo-random noise code (a GPS satellite)", PROB: "probability", PROC: "procedure",
  PROCS: "procedures", PROP: "propeller", PSGR: "passenger", PSN: "position", PT: "procedure turn", PTN: "pattern",
  PUB: "public", PVT: "private", PWR: "power", QDM: "magnetic heading to", QDR: "magnetic bearing from",
  RAD: "radial", RADAR: "radar", RADIAL: "radial", RAIL: "runway alignment indicator lights", RAMP: "ramp",
  RBN: "radio beacon", RCAG: "remote center air/ground", RCAM: "runway condition assessment matrix",
  RCL: "runway centerline", RCLL: "runway centerline lights", RCLS: "runway centerline light system",
  RCO: "remote communications outlet", RCR: "runway condition reading", RCV: "receive", RCVD: "received",
  RCVR: "receiver", RDO: "radio", REC: "recent", RECD: "received", RECON: "reconnaissance",
  REDL: "runway edge lights", REG: "regional", REIL: "runway end identifier lights",
  REILS: "runway end identifier lights", REL: "relative", RELCTD: "relocated", RELCTN: "relocation",
  RELOCATED: "relocated", RENL: "runway end lights", REP: "report", REPL: "replace", REPLD: "replaced",
  REQ: "request", REQD: "required", RESTR: "restriction", RESTRD: "restricted", RFF: "rescue and fire fighting",
  RGNL: "regional", RLLS: "runway lead-in light system", RLTD: "related", RMDR: "remainder", RMK: "remark",
  RMKS: "remarks", RMN: "remain", RMNG: "remaining", RMVD: "removed", RNAV: "area navigation",
  RNP: "required navigation performance", ROUTE: "route", RPT: "report", RPTD: "reported", RQRD: "required",
  RRL: "runway remaining lights", RSA: "runway safety area", RSTD: "restricted", RSTRD: "restored", RTE: "route",
  RTES: "routes", RTHL: "runway threshold lights", RTN: "return", RTP: "right traffic pattern",
  RTZL: "runway touchdown zone lights", RVR: "runway visual range", RVRM: "RVR midpoint", RVRR: "RVR rollout",
  RVRT: "RVR touchdown", RVS: "reverse", RWSL: "runway status lights", RWY: "runway",
  SAA: "special activity airspace", SAR: "search and rescue", SAT: "Saturday", "SAT-SUN": "Saturday and Sunday",
  SBND: "southbound", SCT: "scattered", SCTD: "scattered", SDF: "simplified directional facility", SE: "southeast",
  SEC: "seconds", SECS: "seconds", SECURITY: "security", SEG: "segmented", SEPN: "separation", SEV: "severe",
  SFC: "surface", SFL: "sequenced flashing lights", SFRA: "special flight rules area", SHLD: "should",
  SHLDR: "shoulder", SID: "standard instrument departure", SIG: "significant",
  SIGMET: "significant meteorological information", SIMUL: "simultaneous", SKC: "sky clear", SKD: "scheduled",
  SKED: "scheduled", SLGT: "slight", SLR: "slush on runway", SM: "statute miles", SML: "small", SN: "snow",
  SNGL: "single", SNOWTAM: "snow conditions", SPD: "speed", SPECI: "special weather report",
  SPECIAL: "special notice", SPRL: "spiral", SQ: "squall", SQL: "squall line", SR: "sunrise",
  "SR-SS": "sunrise to sunset", SRND: "surround", SRNDG: "surrounding", SS: "sunset", "SS-SR": "sunset to sunrise",
  SSALF: "SSALS with sequenced flashers", SSALR: "SSALS with RAIL", SSALS: "simplified short ALS",
  SSE: "south-southeast", SSR: "secondary surveillance radar", SSW: "south-southwest",
  STAR: "standard terminal arrival", STD: "standard", STN: "station", STNR: "stationary",
  SUA: "special use airspace", SUBJ: "subject", SUN: "Sunday", SUP: "supplement", SUPP: "supplement",
  SUPPL: "supplement", SUPPS: "supplements", SUSP: "suspended", SVC: "service", SVFR: "special VFR",
  SVN: "space vehicle number", SVR: "severe", SVRL: "several", SW: "southwest", SYS: "system",
  "T/R": "temporary flight restriction", TACAN: "tactical air navigation", TAF: "terminal aerodrome forecast",
  TAR: "terminal area radar", TAS: "true airspeed", TBA: "to be announced",
  TCAS: "traffic collision avoidance system", TDY: "today", TDZ: "touchdown zone", TDZE: "touchdown zone elevation",
  TDZL: "touchdown zone lights", TEL: "telephone", TEMP: "temporary", TEMPO: "temporary", TFC: "traffic",
  TFCA: "traffic area", TFR: "temporary flight restriction", TGL: "touch and go landing", THN: "thin",
  THR: "threshold", THRU: "through", THSD: "thousand", THU: "Thursday", TIL: "until",
  TIS: "traffic information service", "TIS-B": "traffic information service broadcast", TKO: "takeoff",
  TKOF: "takeoff", TKOFS: "takeoffs", TMA: "terminal control area", TMPRY: "temporary", TNGT: "tonight", TOP: "top",
  TPA: "traffic pattern altitude", TPP: "terminal procedures publication", TRACON: "terminal radar approach control",
  TRAF: "traffic", TRANS: "transition", TRK: "track", TRML: "terminal", TRNG: "training",
  TRSA: "terminal radar service area", TSNT: "transient", TSTG: "testing", TUE: "Tuesday",
  TWEB: "transcribed weather broadcast", TWR: "tower", TWRS: "towers", TWY: "taxiway", TWYL: "taxiway lights",
  "U/S": "unserviceable", UA: "unmanned aircraft", UAS: "unmanned aircraft system", UFN: "until further notice",
  UIR: "upper information region", UNATTND: "unattended", UNAVBL: "unavailable", UNAVBLE: "unavailable",
  UNDR: "under", UNKN: "unknown", UNL: "unlimited", UNLGTD: "unlighted", UNLTD: "unlimited", UNMON: "unmonitored",
  UNREL: "unreliable", UNRELBL: "unreliable", UNSKED: "unscheduled", UNSTBL: "unstable", UNUSBL: "unusable",
  UPR: "upper", USBL: "usable", UTC: "UTC", UTIL: "until", UUA: "urgent pilot report", VAR: "variation",
  VASI: "visual approach slope indicator", VC: "vicinity", VCNTY: "vicinity", VCY: "vicinity",
  VDP: "visual descent point", VEH: "vehicle", VEHS: "vehicles", VERT: "vertical", VFP: "visual flight procedure",
  VFR: "visual flight rules", VGSI: "visual glide slope indicator", VIP: "very important person", VIS: "visibility",
  VMC: "visual meteorological conditions", VNAV: "vertical navigation", VOR: "VHF omnidirectional range",
  VORTAC: "VOR + TACAN", VOT: "VOR test facility", VR: "visual route", VSBL: "visible", VSBY: "visibility",
  WAAS: "wide area augmentation system", WBND: "westbound", WED: "Wednesday", WEF: "with effect from", WGT: "weight",
  WI: "within", WIBTWN: "within and between", WID: "width", WIE: "with immediate effect", WINDMILL: "wind turbine",
  WIP: "work in progress", WKDAYS: "weekdays", WKEND: "weekend", WKENDS: "weekends", WKN: "weaken", WND: "wind",
  WNW: "west-northwest", WPD: "wind pattern data", WPT: "waypoint", WR: "wet runway", WRM: "warm", WS: "wind shear",
  WSHFT: "wind shift", WSW: "west-southwest", WT: "wind turbine", WTR: "water", WX: "weather", XCVR: "transceiver",
  XING: "crossing", XNG: "crossing", XPDR: "transponder", XPNDR: "transponder", YDA: "yesterday", YSTDA: "yesterday",
};
